[package]
name = "encryption_tool"
email = "moyamingo1234@gmail.com"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.59"
log = "0.4.20"
rand = "0.8.5"
anyhow = "1.0.75"
